### ISSUE TITLE
Failed connect to hawkular-metrics.172-27-11-10.nip.io:443; Connection refused

### ISSUE THREAD

**Issue by MarcoPalomo** [hector-vido/okd-3.11#2]
Hello,
I tried to connect and register webconsole, but unfortunately I failed. Please let me know what's the way to expose the service.

**Comment by hector-vido** [comment]
You need to add "172.27.11.10 okd.example.com" to your `/etc/hosts` file.

This address "hawkular-metrics.172-27-11-10.nip.io" is only if you deploy the "default" cluster and want to see the metrics graphs on dashboard.
